(()=>{"use strict";
const QUESTION_URL="questions/d1.json";
const DOMAINS={D1:"セキュリティの概念と実践",D2:"アクセス制御",D3:"リスクの識別・監視・分析",D4:"インシデント対応と復旧",D5:"暗号化",D6:"ネットワークと通信のセキュリティ",D7:"システムとアプリケーションのセキュリティ"};
const state={source:[],questions:[],answers:[],index:0,finished:false};let categories,content;
document.addEventListener("DOMContentLoaded",init);
async function init(){categories=document.querySelector("#category-list");content=document.querySelector("#content-area");renderCategories();await loadQuestions()}
function renderCategories(){categories.replaceChildren();Object.entries(DOMAINS).forEach(([code,name])=>{const b=node("button",{className:`category-button ${code==="D1"?"active":""}`,disabled:code!=="D1",type:"button"},[node("span",{className:"category-code",textContent:code}),node("span",{textContent:name}),code!=="D1"?node("span",{className:"soon",textContent:"Soon"}):null]);if(code==="D1")b.addEventListener("click",()=>state.source.length&&start(clone(state.source)));categories.append(b)})}
async function loadQuestions(){renderStatus("問題を読み込んでいます","しばらくお待ちください。");try{const res=await fetch(QUESTION_URL,{cache:"no-store"});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!Array.isArray(data))throw new Error("問題データの形式が正しくありません。");const valid=data.filter(q=>q&&typeof q.question==="string"&&Array.isArray(q.options)&&q.options.length===4&&Number.isInteger(q.correctIndex)&&q.correctIndex>=0&&q.correctIndex<4).slice(0,50);if(!valid.length)throw new Error("有効な問題がありません。");state.source=clone(valid);start(valid)}catch(e){renderError(e)}}
function start(q){state.questions=clone(q);state.answers=new Array(q.length).fill(null);state.index=0;state.finished=false;render()}
function render(){if(state.finished)return renderResults();const q=state.questions[state.index],selected=state.answers[state.index],answered=selected!==null,s=stats();const shell=node("div",{className:"quiz-shell"});shell.append(node("div",{className:"session-bar"},[node("div",{className:"counter"},[document.createTextNode("QUESTION "),node("b",{textContent:String(state.index+1)}),document.createTextNode(` / ${state.questions.length}`)]),node("div",{className:"progress"},[node("div",{className:"progress-fill",style:`width:${state.questions.length?(s.answered/state.questions.length)*100:0}%`})]),node("div",{className:"score-mini",textContent:`回答 ${s.answered}　正解 ${s.correct}`})]));const card=node("article",{className:"question-card"});const meta=[q.id||`D1-${String(state.index+1).padStart(3,"0")}`,q.objective||"Domain 1"].filter(Boolean);card.append(node("header",{className:"question-head"},[node("div",{className:"meta-row"},meta.map(x=>node("span",{className:"meta-chip",textContent:x}))),node("h2",{className:"question-text",textContent:q.question})]));const area=node("div",{className:"answer-area"},[node("p",{className:"answer-label",textContent:"最も適切な回答を1つ選択してください"})]);const list=node("div",{className:"options-list",role:"group","aria-label":"選択肢"});q.options.forEach((text,i)=>{const cls=optionClass(i,selected,q.correctIndex);const icon=answered&&i===q.correctIndex?"✓":answered&&i===selected?"×":"";const b=node("button",{className:cls,type:"button",disabled:answered},[node("span",{className:"option-letter",textContent:String.fromCharCode(65+i)}),node("span",{textContent:text}),node("span",{className:"state-icon",textContent:icon})]);b.addEventListener("click",()=>{if(state.answers[state.index]===null){state.answers[state.index]=i;render()}});list.append(b)});area.append(list);if(answered)area.append(feedback(q,selected));area.append(navigation());card.append(area);shell.append(card);content.replaceChildren(shell);window.scrollTo({top:0,behavior:"smooth"})}
function optionClass(i,s,c){if(s===null)return"option-button";if(i===c)return"option-button correct";if(i===s)return"option-button incorrect";return"option-button muted"}
function feedback(q,selected){const ok=selected===q.correctIndex,box=node("section",{className:`feedback ${ok?"is-correct":"is-incorrect"}`});box.append(node("div",{className:"feedback-title"},[node("strong",{textContent:ok?"✓ 正解":"× 不正解"}),!ok?node("span",{textContent:`正解は ${String.fromCharCode(65+q.correctIndex)} です`}):null]));const body=node("div",{className:"feedback-body"});const explanation=typeof q.rationale==="string"?q.rationale:typeof q.explanation==="string"?q.explanation:q.explanation?.correct||"";if(explanation)body.append(node("p",{textContent:explanation}));if(q.hint)body.append(node("div",{className:"hint-box"},[node("strong",{textContent:"EXAM TIP　"}),document.createTextNode(q.hint)]));box.append(body);return box}
function navigation(){const prev=node("button",{className:"btn btn-secondary",type:"button",disabled:state.index===0,textContent:"← 前の問題"});prev.addEventListener("click",()=>{state.index--;render()});const last=state.index===state.questions.length-1;const next=node("button",{className:"btn btn-primary",type:"button",textContent:last?"結果を見る":"次の問題 →"});next.addEventListener("click",()=>{if(last)state.finished=true;else state.index++;render()});return node("div",{className:"navigation"},[prev,next])}
function renderResults(){const s=stats(),rate=state.questions.length?Math.round(s.correct/state.questions.length*100):0;const review=button("回答を見直す","btn btn-secondary",()=>{state.finished=false;state.index=0;render()});const retry=button("もう一度挑戦","btn btn-secondary",()=>start(state.source));const shuffle=button("シャッフルして挑戦","btn btn-primary",()=>start(shuffled(clone(state.source))));content.replaceChildren(node("section",{className:"result-card"},[node("p",{className:"result-kicker",textContent:"DOMAIN 1 RESULT"}),node("div",{className:"result-score",textContent:`${rate}%`}),node("h2",{textContent:`${state.questions.length}問中 ${s.correct}問正解`}),node("p",{textContent:rate>=85?"十分な理解度です。迷った問題の判断根拠を確認しましょう。":rate>=70?"合格圏を意識できる水準です。誤答を中心に復習しましょう。":"解説を確認し、同じセットへ再挑戦しましょう。"}),node("div",{className:"result-actions"},[review,retry,shuffle])]))}
function stats(){let answered=0,correct=0;state.answers.forEach((a,i)=>{if(a!==null){answered++;if(a===state.questions[i].correctIndex)correct++}});return{answered,correct}}
function renderStatus(title,message){content.replaceChildren(node("div",{className:"loading-panel"},[node("span",{className:"spinner"}),node("div",{},[node("strong",{textContent:title}),node("p",{textContent:message})])]))}
function renderError(e){content.replaceChildren(node("section",{className:"status-panel error-panel"},[node("h2",{textContent:"問題を読み込めませんでした"}),node("p",{textContent:"questions/d1.json の配置と内容を確認してください。"}),node("p",{className:"error-detail",textContent:e.message}),button("再読み込み","btn btn-primary",loadQuestions)]))}
function button(text,cls,fn){const b=node("button",{className:cls,type:"button",textContent:text});b.addEventListener("click",fn);return b}function shuffled(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function clone(v){return typeof structuredClone==="function"?structuredClone(v):JSON.parse(JSON.stringify(v))}
function node(tag,props={},children=[]){const e=document.createElement(tag);Object.entries(props).forEach(([k,v])=>{if(k==="className")e.className=v;else if(k==="textContent")e.textContent=v;else if(k==="style")e.setAttribute("style",v);else if(k in e&&!k.startsWith("aria-"))e[k]=v;else e.setAttribute(k,v)});(Array.isArray(children)?children:[children]).filter(Boolean).forEach(c=>e.append(c));return e}
})();
